FROM alpine:3.20

WORKDIR /bookmarks

RUN apk add --no-cache python3 py3-pip

COPY requirements.txt .

RUN pip install --break-system-packages -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
